[env:esp32s3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
; ajuste a porta do SEGUNDO esp32 (o sniffer) quando plugar
upload_port = COM18
monitor_port = COM18
